# Generated by Django 5.0.2 on 2025-04-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_sample_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
